language: scala
matrix:
  include:
  - scala: 2.10.6
    jdk: oraclejdk7
  - scala: 2.11.8
    jdk: oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION clean package
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
git:
  depth: 1
before_install:
- pip install --user codecov
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publishSigned; };'
- "[[ $TRAVIS_TAG == v[0-9.]* ]] && { sbt sonatypeRelease; };"
- codecov
