language: scala
matrix:
  include:
  - scala: 2.10.6
    jdk: oraclejdk7
  - scala: 2.11.8
    jdk: oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION clean package
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
git:
  depth: 1
before_install:
- openssl aes-256-cbc -K $encrypted_0e676a27a86e_key -iv $encrypted_0e676a27a86e_iv
  -in secring.gpg.enc -out secring.gpg -d
- pip install --user codecov
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publishSigned; };'
- "[[ $TRAVIS_TAG == v[0-9.]* ]] && { sbt sonatypeRelease; };"
- codecov
env:
  global:
  - secure: "W5mPJ2qgc8hqiLMkLSPmR/EAwpve8lp6NRXWAHHgX8SqD/VTY+0+QHjRF9WReIEgq5xdaE7qEisQ7FHXJEM72vQmbyRBo12d554MkcAPWA1BCMZAXaFVt54xzQZ9oD9OHISsYixwhaGOspW+spXfkx10/vjp22QX8S012VdFMhO/UKrN/Pi//cYowDX08oKgBsaiteLHB0FY9pYGETp2XNrKpECfqs3u0HNLRY0mojbCONHHnxzOGFK4oAQg5GkhA6gXNL3htr2kRhnh2hfDQ6zodYXu7VEQ4Nur+FbhzRdEpnSGkmF4GKvngY8Jh7iFLgrTPybH6wMg67nV7a0Lboz/LE6bq7dNy887saPrll4/bM2prqINrxgydD0lOu3rcKmmzQw/JIscfDTqnxGQOkr4O07XM9jT3lJDnaz+4ee7Ufi4MEQwhSF1Ka0/qMEhdM26y3indY3+01TKavI1HIKlkfWyai/OGYUPXmJfU8X1CZTbkXqQ5JmJZ+kfrdlZVCFVjTYkdmdFN6uU/9CYARdJncW/uPCCDqQNKaLjtG1dzirAAtXvyQqC/D2NYxIE69dcx2m2bEJ8Pp68SFzYyHkEFvRXGoKZuE5Zx5rficymAcSbILIXM+1uKNTGOU3C5OaS80Ve+OXzDpG0FLqEyNbDl6+WKxm8jVEC0B4GEhk="
  - secure: "sVtt3Zd6MZ/mUeC/mya/AZQaP16gtyHbHK8MZf+/MXPRUP151mhR7NHOGeF9rpj8TLOIy7yY6yfUL5r1ltKcilsxsAuu1nFVzX9y+WctMTMchItD3Osgr+fLmrcXK9/ifBCtp24Gyr2aiRaxVOjV+vSQVDjSF4HyyEyhOYOXwF//th1k2pe2da7phWubc5MN+epeldT+1ET6dWxdWZtNzbunVQLqBVIfbMIfPzCWdDr1puS6WmbPzwc8ByfUCqUn+2plhKQOE3qFTDuIrQUKhZ0asIDA9P5YNrYpc6k54DuB6ITuz8Jj26ZvkKVFEV2QwJxC7/jXQDr0qpTghOVFn8PReM7Ylcd/qdVfutkZ2NNYE7X5tLvcHooSmbuHlcJt6b7pFElbbp/b28uryyP0PeZ3E2Xq1YCwQpneRbXSiAh3S8m3UB4gPuH9NQ5mW7+0ZLdkctuAs0xWSJ9kstHu8aKCGLH5o3CvMwlvsqRqsgwWMuNMXD9B9YPbzCBJb+IZtz72eA0kq6onHaDgAt48hqDYJEG+/ZxmLusPvZes4bn4ln+xQe7kOzEJmpBdtTqTxmAwZ84UvU7RS93yh2Y7CYeA1idVfGB5zTyhEw4R6FDn5LRByqapWPSfbzbEZkQgh6KqpjRn9vVPaeQ8ASaU5rveha5UYmIrfkdrY7/5CKA="
  - secure: "QGNeI2NL1/LsL+ZErLyvWnWH2+57JYav9wnELCgFod0DyQhUBFi1dxv25cTwe+NKh4n6f6EOA0Iu0uGa+ZjLA92fKvh4FcR84L7S2e1aMxfSrSXgccBUeaRM2AJTYf6dpUcAV6k+A290mI8BP+NssN16R3w/8II0XbALD1BzdPPfdrQNqeCCGLvDZN5W0cnqlozU6D0X1t3TSwv+O6XONaeBZkC0f4cs1xXw7wCKfAN5gTNO9Ih86q2jYwAg6Tyhmtk/U82zjTK8FlzoLlYk1g4K+npqHA9AGnNI/fWWF1ymlXWFHS4R0g/pXXufXWoZQ6PuqDvbkDZ2WwVqyDBaZZzpt+pLj/ycITOQNqOBiWLsJ7YcN73WjffhLaJAc/0w8iLp6yZzh/NzDSUAmF0dmSmNoLsbZxo8yoGwu3Ya6oCB1G1keSgd7qNhEYqakV2KalFUM+fNHCTGfgbWmvzEvgW3SnIwjv1ef8B5UBL2r+tw+CV1GlZJz/Mr0LdziW/vpBUROoaOs3JFoh+BESm1YuAXcCdnhg/u7Y4Pj+JgwR/K/WRjQMA0ylpdkC6vgdhH9/ZfVvSzpe2ThQov2xGErOorF05dbNfwml3LUE95hGBMUTWqnAL1ET1gsNWOdTTwCrQSQkcqfUwH8Q7OzULyDJ3NYlB+4jjNpdm3fi3t3lk="
